package nmd.primal.sorcery.common.init;

import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

public class ModInfo
{
    // ***************************************************************************** //
    //  Mod Details
    // ***************************************************************************** //
    public static final String MOD_ID           = "primalsorcery";
    public static final String MOD_CONFIG       = "primal/" + MOD_ID;
    public static final String MOD_VERSION      = "@MOD_VERSION@";
    public static final String MC_VERSIONS      = "[1.12.2)";
    public static final String DEPENDENCIES = "required-after:forge@[14.21.1.2400,);"
                                                + "required-after:primal@[0.6.69,);";
    public static final String MOD_CHANNEL = MOD_ID;

    // ***************************************************************************** //
    //  Paths
    // ***************************************************************************** //
    //public static final Marker MOD_MARKER       = MarkerManager.getMarker(MOD_ID);
    //public static final String GUI_FACTORY    = "nmd.primal.sample.client.gui.GuiFactory";
    public static final String COMMON_PROXY     = "nmd.primal.sorcery.common.CommonProxy";
    public static final String CLIENT_PROXY     = "nmd.primal.sorcery.client.ClientProxy";
    public static final String UPDATE_JSON      = "http://insecure.www.nmd.so/update-sample.json";

    // ***************************************************************************** //
    //  IDs
    // ***************************************************************************** //
    public static final int POTION_BASE_ID = 0;
    public static final int WORKTABLE_BASIC = 0;

    // ***************************************************************************** //
    //  Creative Tabs
    // ***************************************************************************** //
    public static CreativeTabs TAB_SORCERY = new CreativeTabs(MOD_ID)
    {
        @Override
        @SideOnly(Side.CLIENT)
        public ItemStack getTabIconItem() {
            return new ItemStack(Items.FLINT);
        }
    };
}
